### ISSUE TITLE
It ocurred a error when import AcuityModel

### ISSUE THREAD

**Issue by MESeraph** [VeriSilicon/acuitylite#4]
ENV(docker):
ubuntu 20.04.3
python 3.8.10

issue:
It ocurred a error when import AcuityModel
```shell
root@b5e3208bd98d:~/acuitylite-main/demo# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from acuitylib.lite.acuitymodel import AcuityModel
2022-03-25 10:43:57.000908: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-25 10:43:57.000966: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-25 10:43:58.632630: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/acuitylib/__init__.py", line 13, in <module>
    from acuitylib.app.medusa.postprocess.postprocess import PostProcess
  File "/usr/local/lib/python3.8/dist-packages/acuitylib/app/medusa/__init__.py", line 4, in <module>
    from acuitylib.app.medusa.quantization import Quantization
  File "acuitylib/app/medusa/quantization.py", line 16, in init acuitylib.app.medusa.quantization
  File "acuitylib/quantization/adaptive_round_optimizer.py", line 4, in init acuitylib.quantization.adaptive_round_optimizer
  File "/usr/local/lib/python3.8/dist-packages/keras/api/_v2/keras/__init__.py", line 8, in <module>
    from keras import __version__
  File "/usr/local/lib/python3.8/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.8/dist-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/usr/local/lib/python3.8/dist-packages/keras/metrics.py", line 24, in <module>
    from keras import activations
  File "/usr/local/lib/python3.8/dist-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/usr/local/lib/python3.8/dist-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/usr/local/lib/python3.8/dist-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizers.py", line 31, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

**Comment by MESeraph** [comment]
i has sloved this problem by install keras==2.6.0 and tensorflow==2.6.0.
