### ISSUE TITLE
Error when exporting to TFLite

### ISSUE THREAD

**Issue by ondrejhennel** [VeriSilicon/acuitylite#7]
When running squeezenet_onnx_test.py or lenet_caffe_test.py or running TFLiteExporter on any model, this error happens:
```
Traceback (most recent call last):
  File "lenet_caffe_test.py", line 57, in <module>
    test_caffe_lenet()
  File "lenet_caffe_test.py", line 38, in test_caffe_lenet
    TFLiteExporter(model).export('export_tflite/float16/lenet.tflite')
  File "acuitylib/lite/exporter.py", line 51, in acuitylib.lite.exporter.TFLiteExporter.export
  File "acuitylib/app/exporter/tflite_case/export_tflite.py", line 78, in acuitylib.app.exporter.tflite_case.export_tflite.ExportTflite.run
  File "acuitylib/app/exporter/tflite_case/lite_model.py", line 322, in acuitylib.app.exporter.tflite_case.lite_model.LiteModel.convert
  File "acuitylib/app/exporter/tflite_case/lite_model.py", line 105, in acuitylib.app.exporter.tflite_case.lite_model.LiteModel.build
  File "acuitylib/app/exporter/tflite_case/lite_tensor.py", line 267, in acuitylib.app.exporter.tflite_case.lite_tensor.LiteTensorTable.build
  File "acuitylib/app/exporter/tflite_case/lite_tensor.py", line 171, in acuitylib.app.exporter.tflite_case.lite_tensor.LiteTensor.build
TypeError: EndVector() takes 1 positional argument but 2 were given
```

**Comment by lileiigithub** [comment]
Thanks for your feedback. It may be too high for the [flatbuffers] version, and you can try [pip3 install flatbuffers==1.12].

**Comment by ondrejhennel** [comment]
Thanks for the reply. Installing flatbuffers 1.12 resolved the issue.
